# Generated by Django 5.2.6 on 2025-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatappTechjays', '0002_chat_delete_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('document', 'Document')], max_length=10),
        ),
    ]
