# Generated by Django 5.2.6 on 2025-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatappTechjays', '0004_chat_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='session_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
