# Generated by Django 5.2.6 on 2025-10-10 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatappTechjays', '0005_remove_chat_session_id_chat_session_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chat',
            name='session_name',
            field=models.CharField(default='Chat 1', max_length=255),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'session_name'], name='ChatappTech_user_id_b828c5_idx'),
        ),
    ]
