# Generated by Django 5.2.6 on 2025-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatappTechjays', '0006_alter_chat_options_alter_chat_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='ChatappTech_user_id_b828c5_idx',
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('document', 'Document')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chat',
            name='session_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
