import json
import os
import tempfile
from typing import Any, Dict
import re
import fitz  # PyMuPDF for PDF fallback
import google.generativeai as genai
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from google.genai.errors import APIError
from langchain.document_loaders import (
    UnstructuredHTMLLoader,
    UnstructuredPDFLoader,
    UnstructuredWordDocumentLoader,
)
from django.core.exceptions import ObjectDoesNotExist

from .forms import SignInForm, SignupForm
from .models import Chat

User = get_user_model()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
else:
    print("⚠️ GEMINI_API_KEY not found in environment variables.")

def rename_session(user: User, old_session_name: str, first_user_message: str) -> str:
    """
    Rename a session using Gemini AI. Fall back to the first message if Gemini fails.
    """
    try:
        # Don't rename if session already has multiple user messages
        if Chat.objects.filter(user=user, session_name=old_session_name, sender="user").count() > 1:
            return old_session_name

        prompt = (
            "Provide a short, descriptive chat title (max 5 words, no quotes):\n"
            f"{first_user_message}"
        )

        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(
            prompt,
            generation_config={"temperature": 0.3, "max_output_tokens": 15}
        )

        new_title = ""
        if response.candidates:
            parts = response.candidates[0].content.parts if response.candidates[0].content else []
            if parts:
                new_title = parts[0].text.strip().replace('"', '').replace("'", "")

        if not new_title:
            raise ValueError("No valid title generated by Gemini")

    except Exception as e:
        print(f"[Gemini Rename Parsing Error] {e}")
        new_title = first_user_message.strip()[:30] or "Untitled Chat"

    # Remove "title:" prefix if present
    if new_title.lower().startswith("title:"):
        new_title = new_title[6:].strip()

    if not new_title:
        new_title = first_user_message.strip()[:30] or "Untitled Chat"

    # Ensure uniqueness
    existing = set(Chat.objects.filter(user=user).values_list('session_name', flat=True))
    counter, base = 2, new_title
    while new_title in existing:
        new_title = f"{base} ({counter})"
        counter += 1

    # Rename session in DB
    Chat.objects.filter(user=user, session_name=old_session_name).update(session_name=new_title)

    return new_title

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data.get('full_name', '')
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email
            if User.objects.filter(username=username).exists():
                messages.error(request, "Email already registered!")
                return redirect('signup')  # Redirect clears form and previous errors
            User.objects.create_user(
                username=username,
                email=email,
                password=password,
                first_name=full_name
            )
            return redirect('signin')  # Redirect clears form
    else:
        form = SignupForm()  # Fresh empty form on GET

    return render(request, 'Chatapp/signup.html', {'form': form})


def signin(request):

    if request.method == "POST":
        form = SignInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user:
                login(request, user)
                #messages.success(request, "Sign In successful!")
                return redirect('chat')
            else:
                messages.error(request, "Invalid email or password!")
                return redirect('signin')
    else:
        form = SignInForm()
    return render(request, 'Chatapp/signin.html', {'form': form})
    
def signout(request):
    logout(request)
    messages.success(request, "Logged out successfully!")
    return redirect('signin')

@login_required(login_url='signin')
def chat(request):
    if request.method == "POST":
        old_session_name = request.session.get('current_session')
        temp_history = request.session.get('temp_chat_history', [])

        # Step 1: Save old chat if there's any history
        if old_session_name and temp_history:
            # Rename session based on first user message
            first_user_msg = next((m['message'] for m in temp_history if m['sender'] == 'user'), "")
            if first_user_msg:
                old_session_name = rename_session(request.user, old_session_name, first_user_msg)

            # Only save if not already saved
            if not Chat.objects.filter(user=request.user, session_name=old_session_name).exists():
                for msg in temp_history:
                    Chat.objects.create(
                        user=request.user,
                        session_name=old_session_name,
                        message=msg['message'],
                        sender=msg['sender']
                    )

        # Step 2: Create a new session name
        i = 1
        new_session_name = f"Chat {i}"
        existing = set(Chat.objects.filter(user=request.user).values_list('session_name', flat=True))
        while new_session_name in existing:
            i += 1
            new_session_name = f"Chat {i}"

        # Step 3: Update session data
        request.session['current_session'] = new_session_name
        request.session['temp_chat_history'] = []
        request.session['document_context'] = "" 
    # Load current chat and history sessions
    session_name = request.session.get('current_session')
    if not session_name:
        session_name = "Chat 1"
        request.session['current_session'] = session_name
        request.session['temp_chat_history'] = []

    chats = Chat.objects.filter(user=request.user, session_name=session_name).order_by("timestamp")

    # ✅ Fixed: Remove duplicates, preserve order by latest activity
    all_sessions = (
        Chat.objects.filter(user=request.user)
        .exclude(session_name__isnull=True)
        .exclude(session_name="")
        .order_by('-timestamp')
        .values_list('session_name', flat=True)
    )
    seen = set()
    sessions = []
    for name in all_sessions:
        if name not in seen:
            sessions.append(name)
            seen.add(name)

    return render(request, 'Chatapp/chat.html', {
        "chats": chats,
        "session_name": session_name,
        "sessions": sessions
    })

def get_gemini_response(prompt: str) -> str:
    try:
        if not GEMINI_API_KEY:
            return "Bot: API key not configured."
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt)
        if not response.candidates or not response.candidates[0].content.parts:
            return "Bot: Could not generate a valid response."
        return response.candidates[0].content.parts[0].text.strip()
    except APIError:
        return "Bot: API connection error."
    except Exception as e:
        return f"Bot: Error - {e}"

@csrf_exempt
@login_required
def getvalue(request):
    if request.method != "POST":
        return JsonResponse({"error": "Invalid request"}, status=400)

    session_name = request.session.get('current_session') or "Chat 1"
    message, uploaded_file = "", None

    if request.content_type.startswith("multipart/form-data"):
        message = request.POST.get("message", "").strip()
        uploaded_file = request.FILES.get("doc_file")
    else:
        try:
            data = json.loads(request.body)
            message = data.get("message", "").strip()
        except json.JSONDecodeError:
            return JsonResponse({"reply": "Invalid JSON"})

    if not message and not uploaded_file:
        return JsonResponse({"reply": "Please type a message or upload a file!"})

    context_text, old_session_name = "", session_name
    is_first_user = (
        session_name.startswith("Chat ")
        and not any(m for m in request.session.get('temp_chat_history', []) if m['sender'] == 'user')
        and message
    )

    temp_history = request.session.get('temp_chat_history', [])

    # ✅ Handle File Upload & Save to DB (unchanged)
    if uploaded_file:
        temp_file_path = ""
        try:
            suffix = os.path.splitext(uploaded_file.name)[1] or ".tmp"
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                for chunk in uploaded_file.chunks():
                    tmp.write(chunk)
                temp_file_path = tmp.name

            file_text = ""
            if uploaded_file.name.lower().endswith(".docx"):
                loader = UnstructuredWordDocumentLoader(temp_file_path)
                docs = loader.load()
                file_text = "\n".join([d.page_content for d in docs])
            elif uploaded_file.name.lower().endswith((".html", ".htm")):
                loader = UnstructuredHTMLLoader(temp_file_path)
                docs = loader.load()
                file_text = "\n".join([d.page_content for d in docs])
            elif uploaded_file.name.lower().endswith(".pdf"):
                try:
                    loader = UnstructuredPDFLoader(temp_file_path)
                    docs = loader.load()
                    file_text = "\n".join([d.page_content for d in docs])
                except Exception:
                    try:
                        with fitz.open(temp_file_path) as pdf_doc:
                            pages = [p.get_text("text") for p in pdf_doc]
                            file_text = "\n".join(pages)
                    except Exception:
                        file_text = "⚠️ Unable to extract readable text from PDF."
            else:
                file_text = f"📄 Uploaded file: {uploaded_file.name} (unsupported type)"

            document_log = f"📄 Uploaded: {uploaded_file.name} (content used for context)"
            temp_history.append({"sender": "document", "message": document_log})

            Chat.objects.create(user=request.user, session_name=session_name, sender="document", message=document_log)
            request.session['document_context'] = file_text

        except Exception:
            return JsonResponse({"reply": "File processing failed!"})
        finally:
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)

    # ✅ Save user message (unchanged)
    if message:
        temp_history.append({"sender": "user", "message": message})
        Chat.objects.create(user=request.user, session_name=session_name, sender="user", message=message)

    if is_first_user:
        new_title = rename_session(request.user, old_session_name, message)
        request.session['current_session'] = new_title
        session_name = new_title

    # ✅ Fetch FULL chat history (unchanged)
    full_history = Chat.objects.filter(user=request.user, session_name=session_name).order_by("timestamp")
    history_context = ""
    for chat_msg in full_history:
        history_context += f"{chat_msg.sender.capitalize()}: {chat_msg.message}\n"

    # ✅ Extract mode from frontend (NEW ADDITION)
    mode = request.POST.get("mode", "")

    document_context = request.session.get('document_context', "")

    # ✅ Mode Logic Injection (NEW)
    if mode == "ChatGPT Like Application":
        document_context = ""  # Ignore document context fully

    elif mode == "Document Upload" and not request.session.get('document_context'):
        return JsonResponse({"reply": "❌ Please upload a document first before asking.If you need to know outside of the document please click ChatGPT Like Application", "session_name": session_name})

    # ✅ Detect extraction keywords (unchanged)
    extraction_keywords = ["summarize", "extract", "explain", "overview", "key points", "highlights", "analyze"]
    is_extraction_mode = any(keyword in message.lower() for keyword in extraction_keywords)

    # ✅ Prompt generation (unchanged except document_context check)
    if document_context:
        if is_extraction_mode:
            prompt = f"""
            You are a document analysis assistant. Use the document content to intelligently answer:

            📄 DOCUMENT CONTENT:
            {document_context}

            🧠 CHAT HISTORY:
            {history_context}

            ❓ USER REQUEST:
            {message}

            ✅ Provide a helpful explanation or structured summary.
            """
        else:
            prompt = f"""
            You are a strict document-based Q&A assistant. 
            You MUST only answer from the provided document content. DO NOT generate outside answers.

            📄 DOCUMENT CONTENT:
            {document_context}

            🧠 CHAT HISTORY:
            {history_context}

            ❓ USER QUESTION:
            {message}

            🎯 If answer NOT found inside document, strictly reply: ❌ Not found in document
            """
    else:
        prompt = f"{history_context}\nUser: {message}"

    # ✅ Get Bot Reply (unchanged)
    bot_reply = get_gemini_response(prompt)

    temp_history.append({"sender": "bot", "message": bot_reply})
    Chat.objects.create(user=request.user, session_name=session_name, sender="bot", message=bot_reply)

    request.session['temp_chat_history'] = temp_history

    return JsonResponse({"reply": bot_reply, "session_name": session_name})

@login_required
def load_session(request, session_name: str):
    chats = Chat.objects.filter(user=request.user, session_name=session_name).order_by("timestamp")
    data = [{"sender": c.sender, "message": c.message} for c in chats]
    request.session['current_session'] = session_name
    return JsonResponse({"chats": data, "session_name": session_name})

@login_required
@csrf_exempt
def ajax_delete_session(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            session_name = data.get("session_name", "")
            if not session_name:
                return JsonResponse({"deleted": False, "error": "No session name"}, status=400)

            # ✅ Only delete chats with the exact session name
            Chat.objects.filter(user=request.user, session_name=session_name).delete()

            # ✅ Clear session if it was the current one
            if request.session.get('current_session') == session_name:
                request.session['current_session'] = None

            return JsonResponse({"deleted": True})

        except json.JSONDecodeError:
            return JsonResponse({"deleted": False, "error": "Invalid JSON in request body."}, status=400)
        except Exception:
            return JsonResponse({"error": "An unexpected error occurred. Please try again later."}, status=500)

    return JsonResponse({"deleted": False, "error": "Invalid request"}, status=400)
